### ISSUE TITLE
Hex package

### ISSUE THREAD

**Issue by waisbrot** [tuncer/re2#25]
Would you be up for publishing this in [Hex](https://hex.pm)? I see Jiffy's there, so foreign-code-containing packages are possible.

**Comment by tuncer** [comment]
Sure, but I'd need a volunteer to own the hex entry and upload releases.

**Comment by tuncer** [comment]
Sure, but I'd need a volunteer with an account to own the hex entry and upload releases. Would you be willing to?

**Comment by waisbrot** [comment]
I've got a Hex account and have published packages there. I'd be happy to handle it for you. I'll get it published and if you decide to create an account at some point I can give you either sole or shared control.

**Comment by tuncer** [comment]
Cool, thanks. Let me when you're done, and I'll update the README with instructions for rebar, mix and erlang.mk.

**Comment by waisbrot** [comment]
Done! PR #26 shows what I did to make it publish, FYI (not necessary to merge it if you don't want to move the .app file)

**Comment by tuncer** [comment]
Thanks, merged and released 1.7.9. I assume the version in hex.pm is based solely on the app file and that the project prefixes release tags with `v` as in `vX.Y.Z` is of no concern. Please let me know if the new README is good.
