### ISSUE TITLE
Add rebar3 support

### ISSUE THREAD

**Issue by tuncer** [tuncer/re2#8]
Implement dynamic rebar.config.script that works with both rebar and rebar3.

**Comment by matehat** [comment]
:+1: please add this

**Comment by tuncer** [comment]
Work in progress: https://github.com/tuncer/re2/compare/rebar3

**Comment by tuncer** [comment]
Merged to master, and if you followed the thread on the rebar list, you might be aware that there's some unresolved issues with rebar3 generally, but re2 now build with either rebar2 or rebar3.

**Comment by tuncer** [comment]
@matehat, does it work for you?

**Comment by matehat** [comment]
Thanks @tuncer immensely for your work. I'll double check on my end, but I think everything should be fine! :+1:

**Comment by tuncer** [comment]
Implemented in 1.4.0.
